name: Update README

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update README with latest activity
        uses: jamesgeorge007/github-activity-readme@v1
        with:
          COMMIT_MSG: 'Updated README with latest activity'
          GH_USERNAME: PoornaSri26
      
      - name: Update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/poornasri26"
      
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update README with latest activity'
          branch: main
